from .orders.airline import Airline
from .orders.avaible_flight import AvailableFlight
from .orders.user import User
from .orders.connected_flight import ConnectedFlight
from .orders.user_purchase_history import UserPurchaseHistory
from .orders.tickets import Tickets
from .orders.info_for_buyed_tickets import InfoForBuyedTickets
from .orders.airport import Airport
from .orders.avaible_flight_has_avaible_weight import AvailableFlightsHasAvaibleWeight
from .orders.avaible_weight import AvaibleWeight
