COMMON: &common
  DEBUG: False
  SQLALCHEMY_TRACK_MODIFICATIONS: False

development:
  <<: *common
  DEBUG: True
  SQLALCHEMY_DATABASE_URI: 'mysql://{0}:{1}@localhost/sky_scanner'

production:
  <<: *common
  SQLALCHEMY_DATABASE_URI: 'mysql://{0}:{1}@localhost/sky_scanner'

ADDITIONAL_CONFIG:
  MYSQL_ROOT_USER: root
  MYSQL_ROOT_PASSWORD: root
